# Site settings
title: "Shadow"
tagline: "real applications, simulated networks"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://shadow.github.io/"

# Build settings
markdown: kramdown

colors:  #in hex code if not noted else
  primary: "#2b5c70"
  secondary: "#1c212b"
  link: "#60c1c4"
  link_hover: "#d5f5eb"
  footer_heading: "#ffffff"
  footer_content: "#2b5c70"

# Users information
users:
  - name: georgetown
    url: https://security.cs.georgetown.edu/
    img: georgetown.png
  - name: kuleuven
    url: http://www.esat.kuleuven.be/cosic/
    img: kuleuven.png
  - name: tor
    url: https://www.torproject.org/
    img: tor.jpg
  - name: cambridge
    url: https://www.cl.cam.ac.uk/research/security
    img: cambridge.gif
  - name: uiuc
    url: http://hatswitch.org/~nikita
    img: uiuc.gif
  - name: umn
    url: https://www-users.cs.umn.edu/~hopper/
    img: umn.jpg
  - name: nrl
    url: https://www.nrl.navy.mil/itd/chacs/5543
    img: nrl.png
    
